//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ERP_Palmeiras_RH.Models
{
    public partial class CartaoPonto
    {
        public int Id { get; set; }
        public int Mes { get; set; }
        public int Ano { get; set; }
    }
    
}
