//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ERP_Palmeiras_RH.Models
{
    public partial class DadoPessoal
    {
        public DadoPessoal()
        {
            this.Telefones = new HashSet<Telefone>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string DataNascimento { get; set; }
        public string Sexo { get; set; }
        public long CPF { get; set; }
        public long RG { get; set; }
        public string CLT { get; set; }
        public string Email { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual ICollection<Telefone> Telefones { get; set; }
    }
    
}
