//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ERP_Palmeiras_RH.Models
{
    public partial class EntradasCartaoPonto
    {
        public int Id { get; set; }
        internal int cartoesPontoId { get; set; }
        public long Entrada { get; set; }
        public long Saida { get; set; }
    
        public virtual CartaoPonto CartaoPonto { get; set; }
    }
    
}
