//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_RH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico : Funcionario
    {
        public string CRM { get; set; }
        private int EspecialidadeId { get; set; }
    
        public virtual Especialidade Especialidade { get; set; }
    }
}
