//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_RH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int Id { get; set; }
        public double Salario { get; set; }
        public double Adicionais { get; set; }
        public double Descontos { get; set; }
        public double Total { get; set; }
        public System.DateTime DataPagamento { get; set; }
        public string Cargo { get; set; }
        internal int funcionariosId { get; set; }
        public long DataOrdem { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
