//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_BI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatorio
    {
        public Relatorio()
        {
            this.Tipo = new TipoRelatorioWrapper();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public long DataInicio { get; set; }
        public long DataFim { get; set; }
        public string UrlImagem { get; set; }
        public int UsuarioId { get; set; }
        public long DataModificacao { get; set; }
    
        public TipoRelatorioWrapper Tipo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
