//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_LA.Financeiro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Financeiro.MedSoftSoap")]
    public interface MedSoftSoap {
        
        // CODEGEN: Generating message contract since element name banco from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pagarFunc", ReplyAction="*")]
        ERP_Palmeiras_LA.Financeiro.pagarFuncResponse pagarFunc(ERP_Palmeiras_LA.Financeiro.pagarFuncRequest request);
        
        // CODEGEN: Generating message contract since element name nomesExames from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/receberServico", ReplyAction="*")]
        ERP_Palmeiras_LA.Financeiro.receberServicoResponse receberServico(ERP_Palmeiras_LA.Financeiro.receberServicoRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comprarEquipamento", ReplyAction="*")]
        ERP_Palmeiras_LA.Financeiro.comprarEquipamentoResponse comprarEquipamento(ERP_Palmeiras_LA.Financeiro.comprarEquipamentoRequest request);
        
        // CODEGEN: Generating message contract since element name descricao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comprarMaterial", ReplyAction="*")]
        ERP_Palmeiras_LA.Financeiro.comprarMaterialResponse comprarMaterial(ERP_Palmeiras_LA.Financeiro.comprarMaterialRequest request);
        
        // CODEGEN: Generating message contract since element name descricao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/contaAPagar", ReplyAction="*")]
        ERP_Palmeiras_LA.Financeiro.contaAPagarResponse contaAPagar(ERP_Palmeiras_LA.Financeiro.contaAPagarRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cadastraEspecialidade", ReplyAction="*")]
        ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeResponse cadastraEspecialidade(ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pagarFuncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pagarFunc", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.pagarFuncRequestBody Body;
        
        public pagarFuncRequest() {
        }
        
        public pagarFuncRequest(ERP_Palmeiras_LA.Financeiro.pagarFuncRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pagarFuncRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dataPrevista;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string banco;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string agencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contaCorrente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int idSolicitacao;
        
        public pagarFuncRequestBody() {
        }
        
        public pagarFuncRequestBody(System.DateTime dataPrevista, double valor, string banco, string agencia, string contaCorrente, int idSolicitacao) {
            this.dataPrevista = dataPrevista;
            this.valor = valor;
            this.banco = banco;
            this.agencia = agencia;
            this.contaCorrente = contaCorrente;
            this.idSolicitacao = idSolicitacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pagarFuncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pagarFuncResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.pagarFuncResponseBody Body;
        
        public pagarFuncResponse() {
        }
        
        public pagarFuncResponse(ERP_Palmeiras_LA.Financeiro.pagarFuncResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pagarFuncResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool pagarFuncResult;
        
        public pagarFuncResponseBody() {
        }
        
        public pagarFuncResponseBody(bool pagarFuncResult) {
            this.pagarFuncResult = pagarFuncResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receberServicoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receberServico", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.receberServicoRequestBody Body;
        
        public receberServicoRequest() {
        }
        
        public receberServicoRequest(ERP_Palmeiras_LA.Financeiro.receberServicoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class receberServicoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_Palmeiras_LA.Financeiro.ArrayOfString nomesExames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeEspecialidade;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime dataServico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CPF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        public receberServicoRequestBody() {
        }
        
        public receberServicoRequestBody(ERP_Palmeiras_LA.Financeiro.ArrayOfString nomesExames, string nomeEspecialidade, System.DateTime dataServico, string CPF, string nome, string email) {
            this.nomesExames = nomesExames;
            this.nomeEspecialidade = nomeEspecialidade;
            this.dataServico = dataServico;
            this.CPF = CPF;
            this.nome = nome;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receberServicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receberServicoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.receberServicoResponseBody Body;
        
        public receberServicoResponse() {
        }
        
        public receberServicoResponse(ERP_Palmeiras_LA.Financeiro.receberServicoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class receberServicoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool receberServicoResult;
        
        public receberServicoResponseBody() {
        }
        
        public receberServicoResponseBody(bool receberServicoResult) {
            this.receberServicoResult = receberServicoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarEquipamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprarEquipamento", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.comprarEquipamentoRequestBody Body;
        
        public comprarEquipamentoRequest() {
        }
        
        public comprarEquipamentoRequest(ERP_Palmeiras_LA.Financeiro.comprarEquipamentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class comprarEquipamentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descricao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nserie;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dataPrevista;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string banco;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string agencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string contaCorrente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int idSolicitacao;
        
        public comprarEquipamentoRequestBody() {
        }
        
        public comprarEquipamentoRequestBody(string nome, string descricao, string nserie, System.DateTime dataPrevista, double valor, string banco, string agencia, string contaCorrente, int idSolicitacao) {
            this.nome = nome;
            this.descricao = descricao;
            this.nserie = nserie;
            this.dataPrevista = dataPrevista;
            this.valor = valor;
            this.banco = banco;
            this.agencia = agencia;
            this.contaCorrente = contaCorrente;
            this.idSolicitacao = idSolicitacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarEquipamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprarEquipamentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.comprarEquipamentoResponseBody Body;
        
        public comprarEquipamentoResponse() {
        }
        
        public comprarEquipamentoResponse(ERP_Palmeiras_LA.Financeiro.comprarEquipamentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class comprarEquipamentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool comprarEquipamentoResult;
        
        public comprarEquipamentoResponseBody() {
        }
        
        public comprarEquipamentoResponseBody(bool comprarEquipamentoResult) {
            this.comprarEquipamentoResult = comprarEquipamentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprarMaterial", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.comprarMaterialRequestBody Body;
        
        public comprarMaterialRequest() {
        }
        
        public comprarMaterialRequest(ERP_Palmeiras_LA.Financeiro.comprarMaterialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class comprarMaterialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dataPrevista;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descricao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string banco;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string agencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string contaCorrente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int idSolicitacao;
        
        public comprarMaterialRequestBody() {
        }
        
        public comprarMaterialRequestBody(System.DateTime dataPrevista, double valor, string descricao, string banco, string agencia, string contaCorrente, int idSolicitacao) {
            this.dataPrevista = dataPrevista;
            this.valor = valor;
            this.descricao = descricao;
            this.banco = banco;
            this.agencia = agencia;
            this.contaCorrente = contaCorrente;
            this.idSolicitacao = idSolicitacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprarMaterialResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.comprarMaterialResponseBody Body;
        
        public comprarMaterialResponse() {
        }
        
        public comprarMaterialResponse(ERP_Palmeiras_LA.Financeiro.comprarMaterialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class comprarMaterialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool comprarMaterialResult;
        
        public comprarMaterialResponseBody() {
        }
        
        public comprarMaterialResponseBody(bool comprarMaterialResult) {
            this.comprarMaterialResult = comprarMaterialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contaAPagarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contaAPagar", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.contaAPagarRequestBody Body;
        
        public contaAPagarRequest() {
        }
        
        public contaAPagarRequest(ERP_Palmeiras_LA.Financeiro.contaAPagarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class contaAPagarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dataPrevista;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descricao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string banco;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string agencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string contaCorrente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int idSolicitacao;
        
        public contaAPagarRequestBody() {
        }
        
        public contaAPagarRequestBody(System.DateTime dataPrevista, double valor, string descricao, string banco, string agencia, string contaCorrente, int idSolicitacao) {
            this.dataPrevista = dataPrevista;
            this.valor = valor;
            this.descricao = descricao;
            this.banco = banco;
            this.agencia = agencia;
            this.contaCorrente = contaCorrente;
            this.idSolicitacao = idSolicitacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contaAPagarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contaAPagarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.contaAPagarResponseBody Body;
        
        public contaAPagarResponse() {
        }
        
        public contaAPagarResponse(ERP_Palmeiras_LA.Financeiro.contaAPagarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class contaAPagarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool contaAPagarResult;
        
        public contaAPagarResponseBody() {
        }
        
        public contaAPagarResponseBody(bool contaAPagarResult) {
            this.contaAPagarResult = contaAPagarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cadastraEspecialidadeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cadastraEspecialidade", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeRequestBody Body;
        
        public cadastraEspecialidadeRequest() {
        }
        
        public cadastraEspecialidadeRequest(ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cadastraEspecialidadeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        public cadastraEspecialidadeRequestBody() {
        }
        
        public cadastraEspecialidadeRequestBody(string nome) {
            this.nome = nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cadastraEspecialidadeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cadastraEspecialidadeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeResponseBody Body;
        
        public cadastraEspecialidadeResponse() {
        }
        
        public cadastraEspecialidadeResponse(ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cadastraEspecialidadeResponseBody {
        
        public cadastraEspecialidadeResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MedSoftSoapChannel : ERP_Palmeiras_LA.Financeiro.MedSoftSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MedSoftSoapClient : System.ServiceModel.ClientBase<ERP_Palmeiras_LA.Financeiro.MedSoftSoap>, ERP_Palmeiras_LA.Financeiro.MedSoftSoap {
        
        public MedSoftSoapClient() {
        }
        
        public MedSoftSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MedSoftSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedSoftSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedSoftSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_Palmeiras_LA.Financeiro.pagarFuncResponse ERP_Palmeiras_LA.Financeiro.MedSoftSoap.pagarFunc(ERP_Palmeiras_LA.Financeiro.pagarFuncRequest request) {
            return base.Channel.pagarFunc(request);
        }
        
        public bool pagarFunc(System.DateTime dataPrevista, double valor, string banco, string agencia, string contaCorrente, int idSolicitacao) {
            ERP_Palmeiras_LA.Financeiro.pagarFuncRequest inValue = new ERP_Palmeiras_LA.Financeiro.pagarFuncRequest();
            inValue.Body = new ERP_Palmeiras_LA.Financeiro.pagarFuncRequestBody();
            inValue.Body.dataPrevista = dataPrevista;
            inValue.Body.valor = valor;
            inValue.Body.banco = banco;
            inValue.Body.agencia = agencia;
            inValue.Body.contaCorrente = contaCorrente;
            inValue.Body.idSolicitacao = idSolicitacao;
            ERP_Palmeiras_LA.Financeiro.pagarFuncResponse retVal = ((ERP_Palmeiras_LA.Financeiro.MedSoftSoap)(this)).pagarFunc(inValue);
            return retVal.Body.pagarFuncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_Palmeiras_LA.Financeiro.receberServicoResponse ERP_Palmeiras_LA.Financeiro.MedSoftSoap.receberServico(ERP_Palmeiras_LA.Financeiro.receberServicoRequest request) {
            return base.Channel.receberServico(request);
        }
        
        public bool receberServico(ERP_Palmeiras_LA.Financeiro.ArrayOfString nomesExames, string nomeEspecialidade, System.DateTime dataServico, string CPF, string nome, string email) {
            ERP_Palmeiras_LA.Financeiro.receberServicoRequest inValue = new ERP_Palmeiras_LA.Financeiro.receberServicoRequest();
            inValue.Body = new ERP_Palmeiras_LA.Financeiro.receberServicoRequestBody();
            inValue.Body.nomesExames = nomesExames;
            inValue.Body.nomeEspecialidade = nomeEspecialidade;
            inValue.Body.dataServico = dataServico;
            inValue.Body.CPF = CPF;
            inValue.Body.nome = nome;
            inValue.Body.email = email;
            ERP_Palmeiras_LA.Financeiro.receberServicoResponse retVal = ((ERP_Palmeiras_LA.Financeiro.MedSoftSoap)(this)).receberServico(inValue);
            return retVal.Body.receberServicoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_Palmeiras_LA.Financeiro.comprarEquipamentoResponse ERP_Palmeiras_LA.Financeiro.MedSoftSoap.comprarEquipamento(ERP_Palmeiras_LA.Financeiro.comprarEquipamentoRequest request) {
            return base.Channel.comprarEquipamento(request);
        }
        
        public bool comprarEquipamento(string nome, string descricao, string nserie, System.DateTime dataPrevista, double valor, string banco, string agencia, string contaCorrente, int idSolicitacao) {
            ERP_Palmeiras_LA.Financeiro.comprarEquipamentoRequest inValue = new ERP_Palmeiras_LA.Financeiro.comprarEquipamentoRequest();
            inValue.Body = new ERP_Palmeiras_LA.Financeiro.comprarEquipamentoRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.descricao = descricao;
            inValue.Body.nserie = nserie;
            inValue.Body.dataPrevista = dataPrevista;
            inValue.Body.valor = valor;
            inValue.Body.banco = banco;
            inValue.Body.agencia = agencia;
            inValue.Body.contaCorrente = contaCorrente;
            inValue.Body.idSolicitacao = idSolicitacao;
            ERP_Palmeiras_LA.Financeiro.comprarEquipamentoResponse retVal = ((ERP_Palmeiras_LA.Financeiro.MedSoftSoap)(this)).comprarEquipamento(inValue);
            return retVal.Body.comprarEquipamentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_Palmeiras_LA.Financeiro.comprarMaterialResponse ERP_Palmeiras_LA.Financeiro.MedSoftSoap.comprarMaterial(ERP_Palmeiras_LA.Financeiro.comprarMaterialRequest request) {
            return base.Channel.comprarMaterial(request);
        }
        
        public bool comprarMaterial(System.DateTime dataPrevista, double valor, string descricao, string banco, string agencia, string contaCorrente, int idSolicitacao) {
            ERP_Palmeiras_LA.Financeiro.comprarMaterialRequest inValue = new ERP_Palmeiras_LA.Financeiro.comprarMaterialRequest();
            inValue.Body = new ERP_Palmeiras_LA.Financeiro.comprarMaterialRequestBody();
            inValue.Body.dataPrevista = dataPrevista;
            inValue.Body.valor = valor;
            inValue.Body.descricao = descricao;
            inValue.Body.banco = banco;
            inValue.Body.agencia = agencia;
            inValue.Body.contaCorrente = contaCorrente;
            inValue.Body.idSolicitacao = idSolicitacao;
            ERP_Palmeiras_LA.Financeiro.comprarMaterialResponse retVal = ((ERP_Palmeiras_LA.Financeiro.MedSoftSoap)(this)).comprarMaterial(inValue);
            return retVal.Body.comprarMaterialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_Palmeiras_LA.Financeiro.contaAPagarResponse ERP_Palmeiras_LA.Financeiro.MedSoftSoap.contaAPagar(ERP_Palmeiras_LA.Financeiro.contaAPagarRequest request) {
            return base.Channel.contaAPagar(request);
        }
        
        public bool contaAPagar(System.DateTime dataPrevista, double valor, string descricao, string banco, string agencia, string contaCorrente, int idSolicitacao) {
            ERP_Palmeiras_LA.Financeiro.contaAPagarRequest inValue = new ERP_Palmeiras_LA.Financeiro.contaAPagarRequest();
            inValue.Body = new ERP_Palmeiras_LA.Financeiro.contaAPagarRequestBody();
            inValue.Body.dataPrevista = dataPrevista;
            inValue.Body.valor = valor;
            inValue.Body.descricao = descricao;
            inValue.Body.banco = banco;
            inValue.Body.agencia = agencia;
            inValue.Body.contaCorrente = contaCorrente;
            inValue.Body.idSolicitacao = idSolicitacao;
            ERP_Palmeiras_LA.Financeiro.contaAPagarResponse retVal = ((ERP_Palmeiras_LA.Financeiro.MedSoftSoap)(this)).contaAPagar(inValue);
            return retVal.Body.contaAPagarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeResponse ERP_Palmeiras_LA.Financeiro.MedSoftSoap.cadastraEspecialidade(ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeRequest request) {
            return base.Channel.cadastraEspecialidade(request);
        }
        
        public void cadastraEspecialidade(string nome) {
            ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeRequest inValue = new ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeRequest();
            inValue.Body = new ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeRequestBody();
            inValue.Body.nome = nome;
            ERP_Palmeiras_LA.Financeiro.cadastraEspecialidadeResponse retVal = ((ERP_Palmeiras_LA.Financeiro.MedSoftSoap)(this)).cadastraEspecialidade(inValue);
        }
    }
}
