//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_LA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraMaterial
    {
        public CompraMaterial()
        {
            this.Status = new StatusCompraWrapper();
        }
    
        public int Id { get; set; }
        public Nullable<long> DataEntrega { get; set; }
        public long DataPrevista { get; set; }
    
        public StatusCompraWrapper Status { get; set; }
    
        public virtual SolicitacaoCompraMaterial SolicitacaoCompraMaterial { get; set; }
    }
}
