//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_LA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipamentoClinica
    {
        public int Id { get; set; }
        public int StatusEquipamento { get; set; }
        public int InventarioId { get; set; }
        public int CodigoAtivo { get; set; }
    
        public virtual Equipamento Equipamento { get; set; }
    }
}
