//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_LA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabricante
    {
        public Fabricante()
        {
            this.Equipamentos = new HashSet<Equipamento>();
            this.Materiais = new HashSet<Material>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CNPJ { get; set; }
    
        public virtual ICollection<Equipamento> Equipamentos { get; set; }
        public virtual ICollection<Material> Materiais { get; set; }
    }
}
