//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_LA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public Inventario()
        {
            this.EquipamentosClinica = new HashSet<EquipamentoClinica>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<EquipamentoClinica> EquipamentosClinica { get; set; }
    }
}
