//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_LA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelLAContainer : DbContext
    {
        public ModelLAContainer()
            : base("name=ModelLAContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Usuario> TblUsuarios { get; set; }
        public DbSet<PendenciaManutencao> TblPendenciasManutencao { get; set; }
        public DbSet<Equipamento> TblEquipamentos { get; set; }
        public DbSet<Fabricante> TblFabricantes { get; set; }
        public DbSet<EquipamentoClinica> TblEquipamentosClinica { get; set; }
        public DbSet<Material> TblMateriais { get; set; }
        public DbSet<MaterialClinica> TblMateriaisClinica { get; set; }
        public DbSet<SolicitacaoManutencao> TblSolicitacoesManutencao { get; set; }
        public DbSet<SolicitacaoCompraEquipamento> TblSolicitacoesCompraEquipamento { get; set; }
        public DbSet<CompraEquipamento> TblCompraEquipamento { get; set; }
        public DbSet<SolicitacaoCompraMaterial> TblSolicitacoesCompraMaterial { get; set; }
        public DbSet<CompraMaterial> TblCompraMaterial { get; set; }
    }
}
