//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_LA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendenciaManutencao
    {
        public int Id { get; set; }
        public string Motivo { get; set; }
        public int UsuarioId { get; set; }
        public int EquipamentoClinicaId { get; set; }
    
        public virtual Menutencao Menutencao { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual EquipamentoClinica EquipamentoClinica { get; set; }
    }
}
