//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_LA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitacaoCompraEquipamento
    {
        public int Id { get; set; }
        public double Preco { get; set; }
        public int Status { get; set; }
        public long DataValidade { get; set; }
        public int EquipamentoId { get; set; }
    
        public virtual CompraEquipamento CompraEquipamento { get; set; }
        public virtual Equipamento Equipamento { get; set; }
    }
}
