//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Palmeiras_LA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.PendenciaManutencao = new HashSet<PendenciaManutencao>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
    
        public virtual ICollection<PendenciaManutencao> PendenciaManutencao { get; set; }
    }
}
